- es_index: toscaelement
  es_type: indexedcapabilitytype
  target_element_id: tosca.capabilities.OperatingSystem
  target_property: architecture
  suggestions: [x86_32, x86_64]

- es_index: toscaelement
  es_type: indexedcapabilitytype
  target_element_id: tosca.capabilities.OperatingSystem
  target_property: type
  suggestions: [linux, aix, mac, windows]

- es_index: toscaelement
  es_type: indexedcapabilitytype
  target_element_id: tosca.capabilities.OperatingSystem
  target_property: distribution
  suggestions:
    - linux
    - debian
    - fedora
    - rhel
    - ubuntu
    - centos
    - gentoo
    - windows server 2003
    - windows server 2008
    - windows server 2012
    - windows server 2016

- es_index: toscaelement
  es_type: indexeddatatype
  target_element_id: alien.datatypes.PortabilityInformation
  target_property: supported_artifacts
  suggestions: []

- es_index: toscaelement
  es_type: indexeddatatype
  target_element_id: alien.datatypes.PortabilityInformation
  target_property: iaas
  suggestions: [ amazon, vsphere, openstack, byon, azure ]

- es_index: toscaelement
  es_type: indexeddatatype
  target_element_id: alien.datatypes.PortabilityInformation
  target_property: orchestrator
  suggestions: [ cloudify3, brooklyn ]